// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.18.1
// source: badger.proto

package proto

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique identifier for the entry.
	Secrets []byte `protobuf:"bytes,2,opt,name=secrets,proto3" json:"secrets,omitempty"` // The data to be stored.
}

func (x *SaveEntriesRequest) Reset() {
	*x = SaveEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEntriesRequest) ProtoMessage() {}

func (x *SaveEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEntriesRequest.ProtoReflect.Descriptor instead.
func (*SaveEntriesRequest) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{0}
}

func (x *SaveEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveEntriesRequest) GetSecrets() []byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type SaveEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation was successful.
}

func (x *SaveEntriesResponse) Reset() {
	*x = SaveEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEntriesResponse) ProtoMessage() {}

func (x *SaveEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEntriesResponse.ProtoReflect.Descriptor instead.
func (*SaveEntriesResponse) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{1}
}

func (x *SaveEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the entry.
}

func (x *GetEntriesRequest) Reset() {
	*x = GetEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesRequest) ProtoMessage() {}

func (x *GetEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetEntriesRequest) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // The ID of the entry.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // The retrieved data.
}

func (x *GetEntriesResponse) Reset() {
	*x = GetEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesResponse) ProtoMessage() {}

func (x *GetEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetEntriesResponse) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntriesResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEntriesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the entry.
}

func (x *DeleteEntriesRequest) Reset() {
	*x = DeleteEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntriesRequest) ProtoMessage() {}

func (x *DeleteEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntriesRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntriesRequest) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation was successful.
}

func (x *DeleteEntriesResponse) Reset() {
	*x = DeleteEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntriesResponse) ProtoMessage() {}

func (x *DeleteEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntriesResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntriesResponse) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique identifier for the entry.
	Secrets []byte `protobuf:"bytes,2,opt,name=secrets,proto3" json:"secrets,omitempty"` // The updated data.
}

func (x *UpdateEntriesRequest) Reset() {
	*x = UpdateEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntriesRequest) ProtoMessage() {}

func (x *UpdateEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntriesRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntriesRequest) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEntriesRequest) GetSecrets() []byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type UpdateEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation was successful.
}

func (x *UpdateEntriesResponse) Reset() {
	*x = UpdateEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntriesResponse) ProtoMessage() {}

func (x *UpdateEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badger_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntriesResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntriesResponse) Descriptor() ([]byte, []int) {
	return file_badger_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_badger_proto protoreflect.FileDescriptor

var file_badger_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x22, 0x3e, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x31, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xc8, 0x02, 0x0a, 0x0d, 0x42, 0x61, 0x64,
	0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x61,
	0x76, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x50, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x1e, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x50, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x1e, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_badger_proto_rawDescOnce sync.Once
	file_badger_proto_rawDescData = file_badger_proto_rawDesc
)

func file_badger_proto_rawDescGZIP() []byte {
	file_badger_proto_rawDescOnce.Do(func() {
		file_badger_proto_rawDescData = protoimpl.X.CompressGZIP(file_badger_proto_rawDescData)
	})
	return file_badger_proto_rawDescData
}

var file_badger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_badger_proto_goTypes = []any{
	(*SaveEntriesRequest)(nil),    // 0: badgerpb.SaveEntriesRequest
	(*SaveEntriesResponse)(nil),   // 1: badgerpb.SaveEntriesResponse
	(*GetEntriesRequest)(nil),     // 2: badgerpb.GetEntriesRequest
	(*GetEntriesResponse)(nil),    // 3: badgerpb.GetEntriesResponse
	(*DeleteEntriesRequest)(nil),  // 4: badgerpb.DeleteEntriesRequest
	(*DeleteEntriesResponse)(nil), // 5: badgerpb.DeleteEntriesResponse
	(*UpdateEntriesRequest)(nil),  // 6: badgerpb.UpdateEntriesRequest
	(*UpdateEntriesResponse)(nil), // 7: badgerpb.UpdateEntriesResponse
}
var file_badger_proto_depIdxs = []int32{
	0, // 0: badgerpb.BadgerService.SaveEntries:input_type -> badgerpb.SaveEntriesRequest
	2, // 1: badgerpb.BadgerService.GetEntries:input_type -> badgerpb.GetEntriesRequest
	4, // 2: badgerpb.BadgerService.DeleteEntries:input_type -> badgerpb.DeleteEntriesRequest
	6, // 3: badgerpb.BadgerService.UpdateEntries:input_type -> badgerpb.UpdateEntriesRequest
	1, // 4: badgerpb.BadgerService.SaveEntries:output_type -> badgerpb.SaveEntriesResponse
	3, // 5: badgerpb.BadgerService.GetEntries:output_type -> badgerpb.GetEntriesResponse
	5, // 6: badgerpb.BadgerService.DeleteEntries:output_type -> badgerpb.DeleteEntriesResponse
	7, // 7: badgerpb.BadgerService.UpdateEntries:output_type -> badgerpb.UpdateEntriesResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_badger_proto_init() }
func file_badger_proto_init() {
	if File_badger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_badger_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SaveEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SaveEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badger_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_badger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badger_proto_goTypes,
		DependencyIndexes: file_badger_proto_depIdxs,
		MessageInfos:      file_badger_proto_msgTypes,
	}.Build()
	File_badger_proto = out.File
	file_badger_proto_rawDesc = nil
	file_badger_proto_goTypes = nil
	file_badger_proto_depIdxs = nil
}
